.TH Canto-daemon 1 "Canto-daemon"

.SH NAME
Canto-daemon \- An extensible RSS aggregation daemon.

.SH COMMAND LINE USAGE

canto-daemon (options)

.SH OPTIONS

.TP
\-V/--version
Print version info and exit.

.TP
\-h/--help
Print usage help

.TP
\-v
Enable verbose logging (debug)

.TP
\-D/--dir [directory]
Change base directory for canto-daemon (default: $XDG_CONFIG_HOME/canto)

.TP
\-n/--nofetch
Do not fetch new content while running (debug).

.TP
\-\-noplugins
Disable all plugins

.TP
\-\-enableplugins 'plugin1 plugin2...'
Enable these plugins (overrides --noplugins)

.TP
\-\-disableplugins 'plugin1 plugin2...'
Disable these plugins

.TP
\-a/--address [IP]
Listen on address in addition to local Unix socket. Use "" for all interfaces.
Defaults to loopback (127.0.0.1)

.TP
\-p/--port [port]
Use port when listening with -a

.SH CONFIGURATION

This daemon manages its own configuration, and should be manipulated through
canto-remote or a client, like canto-curses.

.SH PLUGINS

Plugins are packaged in <prefix>/canto/plugins (i.e. /usr/lib/canto/plugins)
and can be enabled by copying them into your configuration directory (i.e.
$XDG_CONFIG_HOME/canto/plugins). Many of them have configuration in them, so
you may want to open the files to make changes. Here are a few example plugins
included with the canto-daemon source.

.TP
reddit.py
Add content to reddit items. Includes a sort
.B "reddit_score_sort"
that will automatically order items by upvotes.

.TP
sync-rsync.py
An rsync based sync plugin. See header for configuration, can be used to sync
with a remote server via SSH, or with another local filesystem (for
NFS/sshfs/Dropbox/gdrive etc.)

.TP
sync-inoreader.py
Synchronize (most) content with inoreader.com, a service with support for RSS
on the web as well as various mobile devices.

.SH FILES

.TP
.I $XDG_CONFIG_HOME/canto/daemon-log

Canto-daemon log file.

.TP
.I $XDG_CONFIG_HOME/canto/plugins/

Canto-daemon plugins directory

.TP
.I /usr/lib/canto/plugins
Default packaged plugin directory.

.SH HOMEPAGE
http://codezen.org/canto-ng

.SH AUTHOR
Jack Miller <jack@codezen.org>

.SH SEE ALSO
.BR canto-remote (1)
