.TH Canto-remote 1 "Canto-remote"

.SH NAME
Canto-remote \- A basic remote for canto-daemon

.SH COMMAND LINE USAGE

.TP
\-V
Print version info and exit.

.TP
\-D/--dir [directory]
Change base directory for canto-daemon (default: ~/.canto-ng)

.TP
\-a/--address [IP]
Attempt to connect to address instead of local Unix socket

.TP
\-p/--port [port]
Use port when connecting with -a

.SH COMMANDS

Run canto-remote with no arguments to list usage and commands.

.SH HOMEPAGE
http://codezen.org/canto-ng

.SH AUTHOR
Jack Miller <jack@codezen.org>
